### ISSUE TITLE
uma0 support

### ISSUE THREAD

**Issue by taneofpain** [rsn8887/uae4all2#1]
would be great if you could add uma0:// support in addition to ux0:// support so we can use storage on uma0.

**Comment by taneofpain** [comment]
thank you i can now see ux0: and uma0: however when i select uma0: i don't see the directories under UMA0 all I see is ..  whereas when i select ux0: i see the directories under ux0.

**Comment by rsn8887** [comment]
I accidentally compiled the release with the -s (safe mode) flag. I am uploading version 1.61 in the next hour that should fix the issue.

**Comment by rsn8887** [comment]
Done please install 1.61 and test again, it should work now. Thank you!

**Comment by taneofpain** [comment]
i get a 0xffffffe error when i install this one in vitashell. do i need to do something different to install it than the earlier releases?
________________________________

**Comment by rsn8887** [comment]
Reboot Vita, make sure you are in un-safe mode.

**Comment by rsn8887** [comment]
It was my fault. Fixed in 1.62

**Comment by taneofpain** [comment]
thx rebooted. tried molecular shell with unsafe on same error, tried vitashell 1.81 same error.
________________________________

**Comment by rsn8887** [comment]
Yes it was my fault one sec

**Comment by rsn8887** [comment]
Ok now it should work try release 1.62 ;)

**Comment by taneofpain** [comment]
Off to work will try in 9hr

Sent from my iPhone

On Feb 7, 2018, at 8:37 AM, rsn8887 <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok now it should work try release 1.62 ;)

**Comment by taneofpain** [comment]
wonderful thank you very much it works perfectly.
________________________________

**Comment by rsn8887** [comment]
good to hear, closing the issue.
