### ISSUE TITLE
Autoload straight into a Savestate

### ISSUE THREAD

**Issue by GrethTom** [rsn8887/uae4all2#11]
I’ve been using the PSP Vice C64 emulator a lot and a really awesome feature is setting up an autoload savestate.  The way it works is when you select your game file, it loads the settings and goes straight into the autoload savestate without any additional steps.  

The way I could see it working here is by setting up one additional savestate called A or Auto.  When you select the rom file, it would load the settings (as it does today) and if there is an Autoload savestate assigned, it would go straight to that without any additional button clicks.  If you wanted to just restart the system with the same rom files, just go back to the menu and hit RB to reset the system.  I know it’s a big ask but would this be something possible here?

**Comment by rsn8887** [comment]
Implemented in v1.72

**Comment by GrethTom** [comment]
Fantastic, thanks a lot.  Will you be looking to add HDF support in a future update?

**Comment by rsn8887** [comment]
Yes I will also add auto-load to hdf. It was just a bit more complicated.

**Comment by GrethTom** [comment]
Great work, appreciate all you help!

**Comment by rsn8887** [comment]
I made a version that supports hdf auto-savestates. Please try it here:
https://mega.nz/#!IVxyRAyD!vmVGCHJBToitCC5D_WYElacESzNZ418T_cUNlwnzdhY

**Comment by GrethTom** [comment]
Perfect, I’ll give it a try later and will let you know how I get on.

**Comment by GrethTom** [comment]
I’m getting quite a lot of issues in this new version you posted.  Savestate on hdf seem to failing more regularly now.  I like using the hdf file in the DF0 slot which worked well in the previous version just I couldn’t use the saved folder for savestates (using ROMs folder worked) however it doesn’t work at all in the new version.  Also getting issues with CONF files on hdf.  Would recommend not releasing this version.  Happy to test further or give more specific if I can.  Thanks.

**Comment by rsn8887** [comment]
Yes it is true, with all the changes, you cannot put hdf files in df0 anymore. You have to put them in the hdf slot.
