### ISSUE TITLE
HardDisk and Memory Options / More options are identical

### ISSUE THREAD

**Issue by muxi1** [rsn8887/uae4all2#13]
Hi,
"Harddisk and Memory Options" are identical to "More Options". Or did I miss something? (Switch Version)

**Comment by rsn8887** [comment]
No, they are completely different:
"Harddisk and Memory Options":
![harddisk and memory](https://user-images.githubusercontent.com/13071547/48049967-0d3fd100-e166-11e8-8829-d8728fa4c939.jpg)

"More Options:"
![more options](https://user-images.githubusercontent.com/13071547/48049969-0f099480-e166-11e8-9d51-0bf1ad58300f.jpg)

**Comment by muxi1** [comment]
This is also the case with the Vita version, but when I open the Harddisk and Memory Options menu on the Switch version, the More Options menu is called up.

**Comment by muxi1** [comment]
What do I have to do, so that the hdf-files are loaded on the switch version? They are started on the Vita. I have taken over the settings of the Vita version (System.hdf, WHDGamesA-C.hdf), but only the bootscreen of the kickrom is started. Thanks in advance!
