### ISSUE TITLE
Case: Keyboard input is not recognized (Switch).

### ISSUE THREAD

**Issue by wronghands** [rsn8887/uae4all2#14]
Hello,

I encountered this issue trying to run Celtic Legends ([mobygames.com/game/amiga/celtic-legends](url))

There's a language selection screen soon after the boot/before the intro and you're supposed to press the corresponding key but the on screen keyboard presses are not registered by the emulated system including the whdload quit key. Keys assigned to buttons via custom input configuration don't work either. + and - buttons stay responsive. On screen keyboard itself does not become unresponsive and provides visual feedback when the keys are pressed.

![2018111022134500-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/16123640/48308795-62e6f580-e539-11e8-9c9f-a116242faa0d.jpg)

Tested with all chipset, rom, cpu speed, sound and blitter options but obviously not with all possible combinations. I haven't encountered this problem with other software.
 
Tested with registered WHDLoad 18.3 with Celtic Legends slave versions 1.3 and 1.4 as well as from ADFs with the Skid Row release (cracked). I also made a custom WHDLoad slave from the Skid Row crack and the issue persists with all copies.

This slave (1.3) works fine with the Libretro P-UAE 2.6.1 core under RetroArch 1.7.5 on Windows 10, Winuae 4.0.1 on Windows 10 and Amiberry 2.18 with Amibian 1.4 on Raspberry Pi.

I'm running system version 6.1.0 on the Switch installed on SX OS 2.2.1 beta emunand. The actual Switch system version is 4.1.0 but I'm not using it.

Thank you for releasing UAE on Switch.

**Comment by rsn8887** [comment]
Thanks for the report. Do you have this issue with any other games or just with this one?

**Comment by wronghands** [comment]
Hi,

No, it doesn't happen anywhere else with the couple dozen games I've tried
including Iron Lord (from the same programmer / period). Everything else
seems to work fine for me so far except for this odd incident.

Best.

**Comment by wronghands** [comment]
I just tested chips uae4arm on raspberrypi and it didn't reproduce the bug (worked fine without lockups). So far uae4all2 switch is the only emulator I'm having this issue and I don't see it listed in the other thread where you listed the known issues. 

It would be great to know if you consider this as a legitimate bug regardless of your plans to fix it. I'd like to figure out if this issue started here or with a previous project/fork so I'm open to suggestions regarding testing other uae variants.

Also if there's a debug version of your emulator I can use it to provide dumps and logs.

Best.

**Comment by rsn8887** [comment]
I consider this a bug. There's no debug version of the emulator.

Have you tried Google? A quick Google search on this problem revealed the following forum thread (here)[http://eab.abime.net/showthread.php?t=18915]

In the thread, the following is explicitly mentioned
"Moreover, this game *appears* to rely heavily on cycle-exact mode, as I had various odd issues without it."

UAE4All2 doesn't have a cycle-exact mode, and implementing one would be an enormous undertaking. So the few games requiring cycle-exact will simply not work. It looks like Celtic Legends is one of them.

**Comment by rsn8887** [comment]
Thanks for the detailed report. I will look into it.

I just had success getting Virocop AGA to work (bitfield instruction fix).

Maybe this game can also be fixed.

**Comment by rsn8887** [comment]
I tried the savestate trick using WinUAE 0.8.22, but I just got gfx glitches, then a crash. I had to manually rename the savestate from xxx.uss to xxx.adf.asf, where xxx is my Celtic Legends Disk 1 name.

I think the savestates from WinUAE, even very old versions, are not compatible with UAE4All2. There are a bunch of changes by TomB to the savestate code in UAE4All2. Maybe UAE4Arm savestates are more compatible? I don't have a working UAE4Arm install, so I cannot test.

**Comment by rsn8887** [comment]
I found the problem with Celtic Legends and have a fixed version here. Thanks @Tonioni for all the help at eab.abime.net forums.

So this should be fixed in next release.

**Comment by wronghands** [comment]
Thank you very much for the time and effort you've put into solving this! I hope the solution was beneficial for other cases as well.

**Comment by wronghands** [comment]
Confirmed working! Feel free to close if you'd like.
