### ISSUE TITLE
Switch: Minor issues with menu UI options and data files.

### ISSUE THREAD

**Issue by wronghands** [rsn8887/uae4all2#16]
Hello,

I've noticed a few minor inconveniences that don't break the emulator functionality in any way. Could you please look into them when you have the time?

- Adding a "HD Dir" when a hdf file in "HD File 1" is present only works when the "Boot HD" option is set to "off". Trying to add a HD Dir and pressing the - button does not add the directory when any other "Boot HD" option is selected. Once both HD Dir and HD File are added with the "Boot HD" option set to "off" it can then be set to "File 1" and both drives work. After this point however (unless the "Boot HD" option is set to "off" again) removing the "HD Dir" and trying to add another directory (when none is set) by pressing the - button, causes the previously selected directory to be mounted instead. 

- When the "OK" button is set as the A button, pressing the B button in the main menu root opens the "More Options" screen regardless of the highlighted menu item. B button returns to the main menu under other screens including the "More Options" screen so actually spamming that button switches between the main menu and the "More Options" screen. Setting the "OK" button to B button reverses the case but the problem stays intact. This is a confusing user experience.

- There are many unused files in the data folder such as mouse.bmp, joystick.bmp, remapping.bmp, gp2xsplash.bmp, logo dev.xcf. On screen keyboard images seem to be duplicated because they are provided as separate bmp files as well as entire keyboard images like vkbdUSLargeShift.bmp. While I'm not sure if these are used in different cases, some appear to be entirely unused, like vkbd.bmp and vkbdHires.bmp. Having 123 files in total in the data folder is a minor inconvenience when transferring them to Switch over ftp.

Thanks a lot for developing this port.

**Comment by rsn8887** [comment]
This should now all be fixed in v1.75

**Comment by wronghands** [comment]
Thank you!
