### ISSUE TITLE
Sound issues - Psvita

### ISSUE THREAD

**Issue by GitElement77** [rsn8887/uae4all2#19]
Hi,
I have the latest uae4all2 version on my PsVita. Tried a few games and all have the same sound issue. The sound is distorted, slow, and skips every other second or so. 

I've tried different settings for the sound and emulator memory settings etc but nothing helps... Any ideas on settings or is this a general thing? :)

**Comment by rsn8887** [comment]
Can you try if the older version 1.72 shows the same problems?

**Comment by rsn8887** [comment]
I will close this because I cannot reproduce the problem, and haven't heard anything from @GitElement77.
