### ISSUE TITLE
Expanding custom control and save states (and more)

### ISSUE THREAD

**Issue by wronghands** [rsn8887/uae4all2#25]
Hi again,

I've been struggling with a few inconveniences lately and decided make some proposals that may help work around them. I hope they'll make sense to you. 

**Custom controls:**

Custom control sets are great but there are only 3 of them and they're stated inside the configuration files which might be the reason why their number is limited. Is 3 the upper limit? Does this limit exist to prevent bloating of config files?

I think being able to back them up away from the config files in a modular way (exporting) and appending them back to the current config (importing) would solve both issues and also provide a way to name them as a bonus. Here is a mock-up to illustrate that. 

![controls](https://user-images.githubusercontent.com/16123640/50720904-6eabef80-1084-11e9-9a8c-6cefc7d5da43.png)

I wouldn't complain if it's also feasible (bloat-wise) to have more than 3 sets per config in addition to this function (if so, just pretend the numbers continue to the right).

I've placed the import/export options on a separate line because if they were on the same line as "custom sets", highlighting a set and moving the pointer to import/export buttons (by pushing down) wouldn't be intuitive. 

A possible problem with this proposal is that exporting requires the on screen keyboard be accessible within the file browser if the user is going to be able to type a file name. Otherwise the file name can be generated from current date/time but this is far from ideal.

**Save States Alternative 1:**

Current implementation of save states work well for floppies but I'm using .hdf files with hundreds of WHDLoad games in them and I'm stuck with only a few save slots because the emulator thinks I'm playing just -one- big game. I also know about the limitations of using save states with WHDLoad but I use them after the proper slave has loaded and had no crashes/errors so far. 

Would it be possible to increase the number of accessible save states by expanding the save state functionality with save slots like this? Nothing is actually changed for people who prefer the current implementation.

![saves](https://user-images.githubusercontent.com/16123640/50720909-871c0a00-1084-11e9-8e66-08eda145af70.png)

Import to slot - Opens up the file browser to link a state file into a slot.

Export from slot - Does the opposite of the previous. Being able to type a file name would be great otherwise file name can be the file creation date/time until a workaround can be found.

Load state - Same as current implementation.

Save state - Same as current implementation.

Delete state - Same as current implementation OR can be moved inside the file browser screen so that people don't accidentally delete a state they don't intend to.

Location - I'm not sure if this still makes sense but I didn't want to remove existing functionality.

Auto savestate - For floppies, as before.

**Save States Alternative 2:**
Here is a more complex alternative. I designed this with the assumption that the number of slots wouldn't necessarily have a limit and you could scroll the list horizontally, manage the number of slots, link them to state files by importing/exporting. 

![saves1](https://user-images.githubusercontent.com/16123640/50720917-9d29ca80-1084-11e9-83db-12d04d807bde.png)

![saves0](https://user-images.githubusercontent.com/16123640/50720921-a9ae2300-1084-11e9-88fe-f7bee051a06e.png)
Add empty slot - Increments empty slots by 1.

Eject - Unlinks the state file from the highlighted save slot and the font color of the slot changes, indicating that it's now empty. If an empty slot is highlighted (last image), the slot is removed instead (rest of the linked states move up a number). Maybe the button text can also be replaced to "remove" but I don't know how hard it would be.
 
**Save States Alternative 3:**

Separate sections for Floppy and HD save states with a red "read warning" button under the HD save state function that explains the limitations of using save states with WHDLoad. Floppy section with current functionality, HD section with all/some of the newly proposed functions. I'd like to hear your response before trying to prepare another mockup though.
 
 
**Default A500 RAM settings:**

Shouldn't this button on the main menu set the RAM as 512k chip + 512k slow? As of now, it just sets the chip to 1MB. I haven't tested it with this emulator but I used to have a 1MB chip A500+ and some badly programmed games (by the same guy) like Double Dragon and Final Fight insisted on 512k chip + 512k slow to work even with a degraded kickstart so I never managed to run them. I can test this further if you'd like.

**UI fonts:**

Playing with these mock-ups I noticed these weird pseudo-serifs with the UI fonts. It's very likely that these bitmap fonts are being displayed at a different size than they were designed for. 

![serifs](https://user-images.githubusercontent.com/16123640/50721015-fd6d3c00-1085-11e9-94aa-64d29bb11670.png)

Likely a leftover issue from earlier uae4all variants. I know this is nitpicking but a different typeface, even good old topaz at a proper size would have better font anatomy. Topaz would also look more genuinely amiga-ish and having more consistent (not fixed) width characters, provide more predictability when modifying the UI. 

**On screen keyboard:**

Font issue again. The characters don't sit on a baseline and this is bugging me to the point that I'm making my own keymap. It's not finished yet but I'll share it if you're interested. For the time being, here is a dark version of the default one:
[amiga.zip](https://github.com/rsn8887/uae4all2/files/2729243/amiga.zip)

Best.

**Comment by rsn8887** [comment]
Wow! Thanks for the ideas. I love the mockups etc. I will look into these things.

Regarding the limited number of custom control sets it is not a big problem to increase them. I just never thought anyone would need more than 3 per adf. At that time I wasn’t thinking of large hdf files having only one config for many games.

**Comment by rsn8887** [comment]
I am almost done with most of your suggestions.

Regarding the font. You can replace text.bmp with a file of your own design. However, the dimension are hardcoded. So each character is 7 pixels wide and 8 pixels tall. I don't think Topaz will fit into these constraints, but I might be wrong.

**Comment by wronghands** [comment]
Hey, thanks so much for considering my suggestions! I don't know what you've implemented so far I've re-read them myself and noticed something that could potentially lead to a confusing user experience:

> Eject - Unlinks the state file from the highlighted save slot and the font color of the slot changes, indicating that it's now empty. If an empty slot is highlighted (last image), the slot is removed instead **_(rest of the linked states move up a number)_**. 

It all depends on how it's implemented but moving save state numbers around might be confusing. 

Case examples:

1- What I proposed:
- User has 4 save states named "1" "2" "3" and "4". 
- User ejects and removes "3". 
- This leads up to "4" moving to "3". 
- User freaks out.

2- A better option:
- User has 4 save states named "1" "2" "3" and "4". Also empty slots "5" and "6". 
- User ejects "3". There is no remove option because at least one other slot to the right is in use (4).
- User can still remove "5" and "6".

2B- Super-optional additional steps:
- When user quits and relaunches the emulator, empty slots are purged (leads up to "4" moving to "3").
- User doesn't freak out as much (hopefully).

2 looks safe enough but as I said I don't know how you decided to implement this so I'm just speculating. I just don't want to break anything lol.

Also thanks for the tips about the fonts. I hadn't noticed the font file earlier. You're correct about Topaz but I ended up not needing it anyway. It's perfect for the on screen keyboard and I'll work on that next but I'm playing the GUI font for now and I'm ready to post the results.

At first, I tweaked the original font a little bit, fixed some broken pixels as shown below. Then I took some liberties, tried to even out the character width as much as possible by narrowing. It could've been better if I could control the kerning but I'm OK with the results. Github stretches the images though. They look better on the screen.

![comparison](https://user-images.githubusercontent.com/16123640/50805729-b8354e00-12c1-11e9-8dc8-81d305a4ed0a.png)

old look:
![default](https://user-images.githubusercontent.com/16123640/50805744-cc794b00-12c1-11e9-99a3-8915ec650372.jpg)
tweaked:
![tweaked](https://user-images.githubusercontent.com/16123640/50805753-d307c280-12c1-11e9-90fc-907f8eb5a67f.jpg)
narrowed:
![narrow](https://user-images.githubusercontent.com/16123640/50805760-d733e000-12c1-11e9-9ff4-ce1759ef227a.jpg)

I also noticed that the current color palette of the font wasn't very noticeable inside the app and looked blurry inside the actual GUI so I made a black-ish version too. 

tweaked-dark:
![tweakeddark](https://user-images.githubusercontent.com/16123640/50805764-ddc25780-12c1-11e9-908a-25078e480b0c.jpg)

narrow-dark:
![narrowdark](https://user-images.githubusercontent.com/16123640/50805783-e9158300-12c1-11e9-8ac5-826a0f0c2687.jpg)

Here are the files in case anyone is interested:
[fonts.zip](https://github.com/rsn8887/uae4all2/files/2734943/fonts.zip)

I'm getting excited about this and trying to make a theme with kickstart 2.x boot screen colors. The fact that the font file can have colors is nice as well as the stuff in colors.txt. I'm thinking of a more detailed post about it later.

**Comment by rsn8887** [comment]
Awesome! I love the narrow-dark font. I agree about the rainbow pattern not being noticeable in the old font. In fact when I first tested the emulator on my VitaTV I thought my hdmi cable was bad because of those color artifacts.

Do you mind if I include it for the next release? I will give you credit in the Thanks section and the release note, of course.

**Comment by wronghands** [comment]
That'd be great, please do!

**Comment by rsn8887** [comment]
implemented in v1.84

**Comment by rsn8887** [comment]
Thank you! I might increase the number of control sets even more in the future. It is certainly on my mind.

Yes, it is true 1080p in docked mode (and still 720p in handheld mode). That means we get even sharper pixels now in docked mode. The switching between the resolutions happens automatically.
