### ISSUE TITLE
Proposal: On-Screen Keyboard Revisions

### ISSUE THREAD

**Issue by wronghands** [rsn8887/uae4all2#26]
Hi again,

As I wrote earlier, I had a few issues with the on-screen keyboard so I made some alternatives. These images look better when opened in a new tab and zoomed to 100%. Also the color temperature/calibration differs between screens so I mainly trusted the real Switch screen.

![warm](https://user-images.githubusercontent.com/16123640/51091599-9b35ca80-175a-11e9-93e6-697fe14d4d7c.png)
![cool](https://user-images.githubusercontent.com/16123640/51091600-9d982480-175a-11e9-9d94-86cbff36ccdd.png)
![dark](https://user-images.githubusercontent.com/16123640/51091601-9f61e800-175a-11e9-874f-14da9e5d75e9.png)
![screen](https://user-images.githubusercontent.com/16123640/51091603-a2f56f00-175a-11e9-9839-670515c8f65e.png)

- The shape of the return key implied that the cursor would move to the ASDF row when moving left while this wasn't the case. Key shape was also different than the active area so it didn't look right while blinking. Same problem with the enter key. Inactive areas are now greyed out in order to clarify how it actually works. I can make this more obvious. I thought about using transparency but can't with bmp files. Possible with pngs.

- Lowercase letters didn't have a consistent baseline (bottoms were not aligned vertically).

- There were some leftover garbage pixels on the return and the tab keys with a slightly different color. Because of this the old bmp had an extra color pen in their palette.

- Due to their size and the outline stroke around them, the characters occupied too much area within the borders of their key. Having more negative space helps with readability. I removed the vertical borders between the letter keys and either removed them on replaced the strokes with an inoffensive 1 pixel-wide shadow (none in topaz alternatives, none on symbol keys). Also removed the horizontal borders between the numeric keys and the cursor keys are grouped now. Characters are aligned well enough now that excessive borders aren't required. I could've done a better job if I could edit the source code of the keyboard map but I don't have an environment set up to compile the code & won't immediately understand what is what.

- Labels on the system keys were not typographically consistent. 

- Similar looking arrows on the backspace, return and cursor keys work fine on real keyboards because they're physical but it's confusing on an on screen keyboard so I made them a bit different and also made the giant arrows on the shift keys smaller.

As for the choice of fonts, the old keyboard had half-height topaz for the numbers and the F-keys. The F-keys looked massive so I redrew their text smaller but this gave me the idea to use topaz for the letter keys for a more genuine amiga look. I also made some alternatives using the narrow font I made earlier because it looks more consistent with the rest of the menu now. Every other symbol is redrawn.

I'd like to hear your opinion on these modifications. Also if you like anything you see here, please feel free to implement it.

I didn't need to make FR,UK or DE layouts for myself but it won't take too much of my time if anyone needs them.

I'm thinking of making game-themed versions as well as putting them up as a github project so that the updates will be accessible if there'll be updates.

Files:
[new keyboard.zip](https://github.com/rsn8887/uae4all2/files/2753633/new.keyboard.zip)

Best.

**Comment by wronghands** [comment]
Great to hear that, I'll get to work ASAP. Fonts really need to be a bit bulky like topaz. I don't like the anatomy of a few characters like x,y and j with topaz but the rest just feel right. I'll be back with minor revisions and the international keymaps!

**Comment by rsn8887** [comment]
Ok I will start coding the new option.

**Comment by wronghands** [comment]
Almost. Only the German one is left to do!

**Comment by wronghands** [comment]
![github](https://user-images.githubusercontent.com/16123640/51269731-3912da80-1991-11e9-8da0-57c7db322281.png)

All done! I tested them all but there might still be mistakes. The font is not 100% topaz anymore but still close so if there's anything that looks off I'll have another look. 

[new international keyboard.zip](https://github.com/rsn8887/uae4all2/files/2765521/new.international.keyboard.zip)

I also noticed a tiny problem with the way right shift key is blinking in French and German layouts. The active area doesn't cover the entire key. It's like a couple pixels too short from the right. Not a big deal.

Thanks for giving me the opportunity to do this. It was fun!

**Comment by rsn8887** [comment]
Awesome, thanks! I will release a new version tonight! I will try to fix the blinking you mentioned, too.

**Comment by rsn8887** [comment]
I think it also looks awesome.

Ok the warm, cool, and dark keyboards are in v1.90, just released.

**Comment by wronghands** [comment]
I started playing with 1.90 and it works perfectly! I'll keep testing the themed keyboard(s) by overwriting the default one but there's nothing much else to say about this for now that I only have one theme.

I've got a couple quick questions: How hard would it be to get rid of the black borders in the menu so that the background images cover the entire width of the screen? I'll also set up a dev environment hoping to have a better understanding on what's going on underneath. Where in the code should I look at to modify the speed and the animation angle of the animated background?

Cheers

**Comment by rsn8887** [comment]
The size of the menu_screen surface in pixels is given by menu_screen_width and height in menu.cpp.

The screen to contain the menu gfx is opened as prSDLScreen in line 430 of menu.cpp.

The SDL Surface text_screen is used to draw all the menu gfx at 320x240, apart from the hi-res thumbnails. text_screen is blitted onto prSDLScreen with a scaling of 2x. Afterwards, the thumbnail, if it exists is drawn on top of that. This allows hi-res thumbnails and a lo-res menu.

So we simply adjust menu_screen_width to make the menu larger and it will almost work. 

The easiest solution is to draw the background directly onto prSDLScreen (instead of text_screen). Then we draw text_screen on top with a new centering, taking into account the widescreen size. Then the thumbnail centering also has to be fixed, since it is drawn in hi-res after everything else has been drawn.

**Comment by rsn8887** [comment]
I will make a commit so you can see the changes that should make it work.

**Comment by rsn8887** [comment]
Ok I made a commit. It is untested since I don't have my Vita. This should implement widescreen menu backdrops. The menu is now drawn with sharp-bilinear-simple, to make it fill the screen vertically in all cases. Since we are dealing with three resolutions (Vita 960x544, Switch docked 1080p, Switch handheld 720p), this seemed the easiest solution I could come up with.

**Comment by rsn8887** [comment]
I hear you. I use a MacBook for development which makes it all a bit easier, since it has a bash shell and the usual Unix command line tools.

**Comment by rsn8887** [comment]
I implemented the widescreen menu background in 1.91. I think this closes the issue. Thanks for the great work!

**Comment by wronghands** [comment]
Thanks so much!
