### ISSUE TITLE
About mouse support

### ISSUE THREAD

**Issue by wronghands** [rsn8887/uae4all2#27]
Hey rsn8887,

I must say the real keyboard/mouse support is amazing! I thought it'd never be possible to use a real keyboard with switch except for when the system allowed text input. Never saw a real mouse working with switch before, period. I think retroarch should implement this for dosbox ASAP.

I've been trying a few wireless mice and most of them don't work. Logitech M525, Microsoft Windows Mouse 1000, touchpad on Logitech K400 all fail the same way (The keyboard part of K400 is fine). Moving the pointer around is registered like the spamming right mouse button and no pointer movement happens whatsoever. 

My logitech G700s works, even in handheld mode with a USB adapter. It's crazy, I'm using Dopus for managing the files on Switch right now, in handheld mode, with a MOUSE! I don't know what the difference is but the G700s has its own receiver that's different than the unifying receiver that lower end models use and it's kind of a high end mouse.

Still I'm having this weird issue with G700s. The pointer arbitrarily stops when moving down or right as if it has reached the end of the movable area/screen. I never have any problems moving to left or up but this happens all the time with either workbench or games. 

Sometimes the movement is constrained to a tiny zone on the top left, sometimes it works almost all the way to the end of the screen before it stops. When it does, I just wiggle the pointer around a little bit and it recalibrates the boundaries like an uncalibrated analog stick until it happens again, like in 2 seconds or so. I can also force move the pointer with the analog stick on the joycons so maybe this counts as a fixable bug. Are you also having this problem with M187? I think I'll just buy one for the time being if it works well enough. 

PS: I've come across some of your gbatemp posts and tweets about this project. Many thanks for giving me credit, I really appreciate it but some of your @wronghands links are accidentaly targeting to a very old twitter account with the same alias which is not mine. I don't think I was that exact kind of crazy in 2010 to have a frog account on twitter :D Just don't worry about linking at all, I'm just bringing this to your attention because I have no control over that account in case it posts something we don't approve of :O 

Best

**Comment by rsn8887** [comment]
This issue with the mouse boundaries is also happening sometimes for me. It seems to be an issue with the way the operating system is reporting mouse positions. I will try to find a workaround ASAP.

**Comment by rsn8887** [comment]
This will be fixed in next release

**Comment by rsn8887** [comment]
fixed in v1.93
