### ISSUE TITLE
No Gui / Skip Gui problems...

### ISSUE THREAD

**Issue by toman9** [rsn8887/uae4all2#3]
I am trying to implement a switch to skip GUI at start-up.
So far no luck. If I skip the GUI creation and jump straight to emulation-start after init, the app crashes.
Since I have no debugger attached, it is hard to see where this happens.

Any pointers would be greatly appreciated, I am happy to contribute to the code.

**Comment by rsn8887** [comment]
I suggest making minimal changes and just insert an artificial r-trigger pressed key event into the SDL event queue on initial startup. Keep everything as is and just set a variable initialStartup = 1 in main(). Find when the gui code would handle the “r-trigger” key event that causes a reset and emulation start. Before that pollEvent loop where the r-trigger would be handled, you could include something like “if (initialStartup) { initialStartup = 0; “create SDL key down event and SDL_Pushevent and keyup event and SDL_Pushevent ” }

There’s a lot of information online how to create and push a “simulated” SDL key event even if no key is physically pressed.

The code in psp2_touch.c for example simulated mouse up and down events.

**Comment by rsn8887** [comment]
You could make a pull request then I can merge the code
