### ISSUE TITLE
Folder mounted HDs with command line errors

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [rsn8887/uae4all2#32]
Hi

Just started really digging into this emulator. Looks very nice from what I’ve seen so far.

I am having trouble however with HDs mounted  from folders.

I’ve set up some WHDLoad games with very simple startups; cd into a game folder, and launch the WHDLoad slave ... nothing major in there, all simple enough stuff.

I’ve tested the self-contained files in Fs-uae on OSX and there are no issues.

I’ve moved the files over to my Vita via FTP and I mount the drive, reset to boot and everything seems to start in dos.

I am then hit with errors such as “cd failed return code 20” 

Sadly I also seem to have a similar issues when using other folders (such as my AMOS coding setup) , although this returns “assign: file is not executable” 

In each case the failure is the first command of startup-sequence 

From my time using Amiberry on the Pi, is there perhaps a permissions issue here to do with file transfer? Is there a requirement for the files to be located somewhere else where there are the appropriate rights? It does seem strange that ADFs in the folder at ok, but perhaps that simply confirms that the files can be read ok, just not executed on the Amiga side.

I appreciate that HDFs might solve the problem, but they are not really practical for me when I tend to share files (saves etc) between systems , or like to test programs I’m writing on multiple difference emulators.... plus the time consuming element of converting everything.

As an aside, It would also be nice if “save Config for game” was able to detect that my game comes from the HD and not DF0: as this doesn’t seem to give a notification when used this way .

Any thoughts welcomed. Thanks

**Comment by wronghands** [comment]
Hi,

I'll just throw in some troubleshooting tips. Telling us about your Kickstart version and some information about your directory structure would help here. AFAIK FS-UAE is involving in some extra AmigaOS side wizardry when directly booting WHDLoad archives. With a real Amiga or another variant of uae, you don't have the assign commands from your kickstart and the CD command is in the rom from Kickstart 2.0x and onwards. You might want to have them in the C folder or at the root of your boot drive. 

If you already have this sorted out, you might want to check the early startup boot menu for your drives. Reboot with both mouse buttons pressed and you should be able to see your drives listed if they're mounted properly. If you can't get to this screen, try switching to a slower config. If you don't see the drives listed and that you're sure they're shown as mounted in the hard drive configuration screen in uae4all2 then please walk us through the issue with screenshots and the contents of your configuration file.

Best.

**Comment by HoraceAndTheSpider** [comment]
just to clarify, i'm not using the FS-UAE whdload booting feature, i'm just using FS-UAE to check that the installed folder works. (Which they do)  I should probably mention i added the WHDLoad auto-loading function to Amiberry on the Pi, so i do have some expereince in this area, and I am very confident that what i am putting in on the Amiga side should work.

Ultimately all i'm looking to do is add a bootable HD folder - the content should be irrelevant, which is why i added that the AMOS Pro development setup i have, also failed.

I use a kickstart 3.1 rom for this. 

Here is an example of one of the contents: 

```
C
Devs
Libs
S
Savegames
WHDBooter
game

./C:

Assign
Copy
Delete
Dir
DiskInDrive
Execute
GetMouseInput
Info
List
MakeDir
Rename
Search
Type
Version
WHDLoad
Wait
ed
joytest
jst
kgiconload

./Devs:
Kickstarts

./Devs/Kickstarts:

kick33180.A500.RTB
kick33192.A500.RTB
kick34005.A500
kick34005.A500.RTB
kick40063.A600.RTB
kick40068.A1200
kick40068.A1200.RTB
kick40068.A4000.RTB
system-configuration

./Libs:
68040.library
amigaguide.library
amos.library
asl.library
datatypes.library
diskfont.library
explode.library
iff.library
iffparse.library
locale.library
lowlevel.library
mathieeedoubbas.library
mathieeedoubtrans.library
mathieeesingtrans.library
mathtrans.library
medplayer.library
nonvolatile.library
xpkmaster.library

./S:
startup-sequence
whdload.prefs

./Savegames:

./game:
Disk.1
Disk.2
ReadMe
ReadMe.info
SuperCars.highs
SuperCars.info
game.slave
```

I set all games to being  a folder called `game` and use a slave file `game.slave` so that i dont have to write a new startup-sequence every time.

Config file is the default A1200 option on uae4all2, with the HD mounted (which i notice already adds 8meg x3 ram) - nothing else changed.

The folder must be mounted and present, otherwise the startups-sequence wouldnt even attempt to run, but to satisfy the curiosity, i've entered the boot options menu and can confirm the drive is mounted.

I'm afraid there's not much to show in terms of screenshots, i select the A1200 setting, set HD-Dir as the boot drive, and mount the HD folder.

I'm not aware of this "file is ready for archiving" option - is this Windows specific? I copy my files on with FileZilla on OSX, and transfer onto the PS-Vita with molecularShell's FTP server.

I mentioned HDFs as a possible work-around (although work-arounds are not the same as solutions/fixes); this might be agreeable if lots of games could be mounted into a single HDF file, but then you have the issue of setting a specific settings etc, including controls, which is always preferable.

Thanks, I will do some extra checks for the mentioned FTP options based on your comments

**Comment by HoraceAndTheSpider** [comment]
Clocked an answer to this - tried various options on both server and FTP side (including different programmes for both) and it seems it steps from 'auto detection' of the file type - possibly then dropping permissons, or corrupting any amiga script/dos files (including startup-sequence)

Make sure all your amiga files are transferred  as 'binary' and you dont use/allow ASCII transfer if you want to avoid the above issue with HD files.

I hope others find this issue useful for an answer in the future.
