### ISSUE TITLE
Feature Request: Mount LHAs & ZIPs as HD Files

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [rsn8887/uae4all2#34]
I notice you have support for HDFs already. Persumably you are still sharing the HDF reading code from WinUAE upstream.

Please could you enable the mounting of ZIPs and LHA archives as read-only images. The code for handling these in UAE already allows for this.  I appreciate this may require adding the `archivers` modules.

This would allow some games to be played by mounting a 'boot drive' as a folder, and also attaching 'game data' (e.g. a pre-installed WHDLoad game) in distributed format.

Thanks :)

**Comment by rsn8887** [comment]
Just use .hdf. WinUAE might have zip/lha extraction built-in but UAE4All2 doesn't. On Pandora or GP2X, a workaround was used where a shell command was invoked to extract lha and zip files into a temp folder. This worked because those consoles run some kind of linux with a shell. Of course, such a workaround doesn't work on Vita or Switch. There's no support for executing external command-line tools. It was painful enough to get .adz support to work.

**Comment by HoraceAndTheSpider** [comment]
To be clear I am in no way suggesting using an external extractor for this via a system call.

WinUAE (and as a result Amiberry downstream) have this code already included and handle the data direct in memory, so my thought was that was that you would re-use the upstream winuae code.

I understood uae4arm and uae4all shared code base with winuae, or is this only the case with the former?

The compatibility on file system attributions is another reason I believe this would be a useful feature and why I would prefer not to be extracting these files manually.

HDF use may be a future option, but is time consuming to convert files and is a bit dependent of the ease of sharing a boot disk - as per my other request- comes into play (batch converting LHAs won’t carry the boot files)

 I appreciate based on the above this may not be possible at this stage though, which is a shame, but I can understand if the code simply isn’t available downstream. 

Thanks for the explanation

**Comment by rsn8887** [comment]
UAE4All2 is based on a very old UAE version (0.8 or so) with some WinUAE code backported into it later here and there. Amiberry is based on UAE4Arm which is based on a very recent WinUAE version (not sure which).

**Comment by HoraceAndTheSpider** [comment]
Makes sense. Thanks for the clarification.

I think midwan is putting some of winuae 3.x into Amiberry as we speak, but that does likely come with a speed hit, so I always see places where uae4all2 is going to be preferable. 

Happy to close this on this basis, and will look into batch LHA->HDF conversion for a solution with a few tweaks.
