### ISSUE TITLE
Performances issues with some games

### ISSUE THREAD

**Issue by VITOAMOROSO82** [rsn8887/uae4all2#38]
Hi, I am writing to request information regarding the possibility of improving the performances of some games in PS Vita, in particular Sensible World os Soccer (SWOS). The main problem is the too high speed of the game, in fact I have compared the playability with my real Amiga600 using both the floppy and whdload and the speed of the emulator is decently higher. I tried a myriad of settings, if I change the appearance filters a little slows down but the visual quality is really bad, and also the audio. I have tried both the adf and the hdf files on PS Vita, same problem. Also if I use the key combination R + START + DIRECTIONS to put the screen in full screen the game goes even faster, so 4: 3 would be the best choice, even if it is not very playable.

Is there any way to slow down the emulator speed? I have last version installed 1.99. Thanks

**Comment by rsn8887** [comment]
Just use Amiga 500 config and ADF version.

Make sure CPU is set to 68000 7 MHZ.

**Comment by rsn8887** [comment]
Make sure the sound is NOT disabled in the menu. The emulator uses sound to sync the speed.

**Comment by VITOAMOROSO82** [comment]
Ok, going to test now and I'll let you know

**Comment by VITOAMOROSO82** [comment]
Nothing, for me is too fast...The sound is NOT disabled, also I switched between accurate and fast, but never off. I'm trying to use P-UAE but no guide/tutorial for PSVita around, can you help me on this?

**Comment by rsn8887** [comment]
As with almost all open source projects on github, the readme.md is your friend and contains detailed instructions how to use PUAE:
https://github.com/libetro/libretro-uae

**Comment by VITOAMOROSO82** [comment]
Yes sorry, I modified my comment and was able to start with the correct kick names... So I think I'll switch to Puae, thank you very much, very nice work!!! 😉

**Comment by VITOAMOROSO82** [comment]
About the audio in PUAE...In SWOS I'm not able to fix some crappy sound I hear on the menu and during play, I tried different things but no way to fix...

**Comment by VITOAMOROSO82** [comment]
I managed to fix the audio setting the Stereo paramenters to 0%. I can close here, thank you
