### ISSUE TITLE
Android support ?

### ISSUE THREAD

**Issue by ravilrrr** [rsn8887/uae4all2#39]
Did you think about Android support ?

**Comment by rsn8887** [comment]
I have no interest in porting this to Android, sorry. I own zero Android devices, apart from an old Nvidia Shield Portable, which takes forever to boot.

Of course, anyone else is welcome to fork this repo and make an Android port.

In my opinion, Android already has a really nice Amiga emulator called UAE4Arm, so I see no need for this.
