### ISSUE TITLE
Long filename support

### ISSUE THREAD

**Issue by chapas** [rsn8887/uae4all2#4]
I'm using a few of my favorites games from the Amiga TOSEC collection, it's hard to find a zip file that loads, i guess this has to do with file naming. If this is the case can this be corrected?

Regards

**Comment by rsn8887** [comment]
Only adf files are supported.

**Comment by chapas** [comment]
Sorry, you are right, i can't see the extensions, filenames are to long, they are ADF's not ZIP.
I believe that most of the files are 255 characters or less.
If you have the TOSEC collection i can name some that work for me and others that don't, otherwise i would be glad to send you some ADF file for you to test.

**Comment by rsn8887** [comment]
Maybe you can help and test one filename to see what causes it to work and what doesn't? If the total path plus filename is <255 chars it should work. It might have to do with special characters, or the filesystem.

**Comment by chapas** [comment]
Will do and report later.

**Comment by chapas** [comment]
Hello,
i've taken some time to do some tests with filenames and they are not the problem.
Sorry for making you waste your time with a non-existing naming problem.

The real problem must be compatibility, ie: 'Walker (Psygnosis) (1993)'
This ADF file works on WinUAE, but does not work on an Android Shield tablet with Uae4all2-SDL neither on PSVita's uae4all2.

I will try to run this with WHDLoad instead on ADF files.

Thank you for your work for this port on the PSVita.

**Comment by rsn8887** [comment]
Thanks for looking into this.
