### ISSUE TITLE
How to start rom

### ISSUE THREAD

**Issue by SuperSpe** [rsn8887/uae4all2#52]
Sorry for the dumb question.
I copy the kickstart rom and few rom games.
The app runs fine, I select the rom from the menu but nothing happen.
If I hit minus it resets and I see the original amiga image, the hand with the floppy, but nothing happen. If I bring the menu the rom is loaded on the drive....how to start?
thanks

**Comment by rsn8887** [comment]
Press R shoulder button to reset and start the game.

**Comment by SuperSpe** [comment]
I cannot check now but I am suer the if I press reset I see only the hand with the floppy.
How to check if adf is bootable? 
I tried with adf and zip too

**Comment by SuperSpe** [comment]
My bad. The roms were in .ipf
I manage to have another in adf and works 👍
