### ISSUE TITLE
Creating a forwarder for Amiga games on Switch

### ISSUE THREAD

**Issue by locksoft** [rsn8887/uae4all2#53]
Hi, I'm trying to create a forwarder (.NSP) to quickly launch my games from the Switch dashboard, but I can't find a way to make it work.

I'm using this great online tools: https://nsp-forwarder.n8.io/retroarch

I'm able to launch Uae4All2 itself, but not the roms. I've tried to use the retroarc function passing first the rom and then the config file (I think the latter is better, as games may be multi discs).

I hope Uae4All2 could accept a parameter text, so to know what config file to launch, but I'm not sure how and if it could be done.

Can you help me? Thanks.

**Comment by rsn8887** [comment]
I made a new test version of UAE4All2 where this should work with the forwarder here (use the retroarch version): https://nsp-forwarder.n8.io/retroarch

Link to the test version of UAE4All2 where it should work:
https://files.coolatoms.org/uae4all2.nro

To test it, I
- started the emulator normally
- inserted Superfrog disk 1
- saved the config with name "superfrog" using the Config - Save As option in UAE4All2
- I checked that the config was saved to my SD card with the full name /switch/uae4all2/conf/superfrog.conf

I then made myself a forwarder with a Superfrog Icon, using these options:

Core:
/switch/uae4all2/uae4all2.nro
Rom:
/switch/uae4all2/conf/superfrog.conf

When I started the forwarder, Superfrog automatically launched.

Tell me if it works for you. I might make a new official UAE4All2 version soon.

**Comment by locksoft** [comment]
Wow @rsn8887, I've made a Cannon Fodder .nsp package and it perfectly works, you're the best! :)

In the next days I'll do some more test with other games, but I'm sure there shouldn't be any problem, as Cannon Fodder is already complex (it uses 3 floppies).

Many thanks. :)

**Comment by rsn8887** [comment]
Implemented in v2.10
