### ISSUE TITLE
Displaylines conf not taking effect

### ISSUE THREAD

**Issue by GrethTom** [rsn8887/uae4all2#6]
Firstly, love this emulator.  One issue I has spotted, Displaylines gets saved to the conf file however doesn’t take effect.  Looks like presetModeId is being used and the Displaylines override doesn’t take effect.  Happy to provide screenshots and should be very easy to replicate.  Thanks.

**Comment by rsn8887** [comment]
I can confirm this is a bug and will be fixed in next release. Thanks for the clear description. It was exactly like you said. When loading a config, the preset was applied after all config variables had been loaded in. This changed the display lines.

**Comment by GrethTom** [comment]
Perfect, thanks a lot.

**Comment by rsn8887** [comment]
Ok it should be fixed in v1.71, please test it and tell me if it works now for you.
