### ISSUE TITLE
Add HD options to the conf file for use

### ISSUE THREAD

**Issue by GrethTom** [rsn8887/uae4all2#7]
Any chance of adding the ‘Boot HD’ along with ‘HD Dir’ & ‘HD File#’ to the conf file?  There are a few games I have which use HDF and I have to manually configure them each time.  Any help here would be great.

**Comment by rsn8887** [comment]
If you configure hd options and save default config, those options should be automatically loaded whenever you start uae4all2. That’s how I use the hd settings.

When you load a hd and save hdf options (inside the hd menu), then those options should be reloaded whenever you load that same first hdf again.

Is this not what you want? Or did I misunderstand?

**Comment by rsn8887** [comment]
So, you configure your hdf options like you want them, and then select "Save config for current HD". Then, when you load that hdf again, then it should load the config again, including all the hd options. Which options exactly is it not loading?

I just tried
- insert four different hdf files in slots 1-4
- select "Save config for current HD".
- restart uae
- load the first hdf file again
- the saved config is automatically loaded, and all 4 hdf files appear

So it seems to work.

**Comment by GrethTom** [comment]
If you can fix that, it would be epic.  Thanks a lot!

**Comment by rsn8887** [comment]
Yes it will be fixed in next release

**Comment by rsn8887** [comment]
Ok it should be fixed in v1.71, please test it.
