### ISSUE TITLE
Graphical issues in Rock n Roll game

### ISSUE THREAD

**Issue by ghamson** [rsn8887/uae4all2#9]
Hi, there appears to be graphical issues similar to the ones PP Hammer did before you fixed them.

If you have time... could you take a look?

Having tried the various modes... I can’t seem to stop the glitches

Awesome work by the way

Thanks

Giles

**Comment by rsn8887** [comment]
I will take a look. Remember you need to reset the Emulation after changing blitter settings.

**Comment by ghamson** [comment]
I believe I have done that but will check again and report back

**Comment by ghamson** [comment]
I have updated to the latest version 1.70 on my PS Vita fw 3.60... tried all combinations of blitter options along with the sprite collision on/off. (Saving config and resetting each time)

Best option seems to be:
Sprite Collision: Off
Blitter: Immediate

CPU also needs to be set to 7Mhz in order to get the game to run at the correct speed.

If you have time to take a look, I would appreciate but also aware that this is just one game and all others I’ve tried seem to run great

Really appreciate all the effort you have put into this emulator on the Vita

Cheers

Giles

**Comment by rsn8887** [comment]
Thanks for the details I will take a look.

**Comment by rsn8887** [comment]
I got the game to run fine, just not in WHDLoad. But when boot the .adf floppy, using A500 config and Blitter Mode: Normal, it runs perfect.

I have found quite a few games that don't work correctly in WHDLoad, but work fine booting from floppy using A500 config. In WHDLoad, some games either always run too fast, or too slow, or they gfx glitches. If you find a WHDLoad game with glitches, I would always try the .adf version. The loading times are longer, but often it works. And you can use a save state or floppy speed 4x to shorten loading times.

**Comment by rsn8887** [comment]
I decided to leave this issue open until you had a chance to test it.

**Comment by rsn8887** [comment]
I received another report it works. Closing.
